# Generated by Django 3.0.6 on 2020-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('saving_acc', models.CharField(max_length=20, unique=True)),
                ('fixed_acc', models.CharField(max_length=20, unique=True)),
                ('s_balance', models.BigIntegerField()),
                ('f_balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
            ],
        ),
    ]
