# Generated by Django 3.0.6 on 2020-05-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='fixed_acc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='saving_acc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=50),
        ),
    ]
