# Generated by Django 3.0.6 on 2020-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0005_auto_20200522_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fixed_acc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='saving_acc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
