# Generated by Django 3.0.6 on 2020-07-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0006_auto_20200522_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
