# Generated by Django 3.0.6 on 2020-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0008_auto_20200831_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
