# Generated by Django 3.0.6 on 2020-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0009_auto_20200903_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
