# Generated by Django 3.0.6 on 2020-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0010_admin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('query_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=30)),
                ('query_data', models.CharField(max_length=100)),
            ],
        ),
    ]
